### ISSUE TITLE
Improve downsampling

### ISSUE THREAD

**Issue by Lehren** [itslanguage/itslanguage-js#185] opened 2016-12-08 13:35 UTC
https://github.com/jussi-kalliokoski/audiolib.js/

Use this lib or anything better if one is found for better downsampling in `wavepacker.js`

**Comment by joggienl** [comment] 2018-09-03 12:00
Seems outdated, at least the issue is very old imo. Closing time!

**Closed by joggienl** 2018-09-03 12:00 UTC
Labels: enhancement
